language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: UO7Mj7KIH/uEtEtNs6KdMcyc7ilne9AvSs4BB9G5NbwSNYvengOWc/ODEm2HkeWaEyFjFp9SnIzDW4JHrCTa/ANwrVRTEZKv4Gf8Z8wYOOJTrBinzIjkJgg/sn9YxkILJ1lmvMxzX4jnahlh529SGHdWP6rSkaP76+5E4PeyR8M=
